"""Generate a PyInstaller Windows version info file from pyproject.toml."""

from __future__ import annotations

import argparse
import sys
import tomllib
from pathlib import Path
from typing import Any


def _parse_version(version_str: str) -> tuple[int, int, int, int]:
    parts = [int(p) for p in version_str.split(".")]
    while len(parts) < 4:
        parts.append(0)
    return (parts[0], parts[1], parts[2], parts[3])


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Generate a PyInstaller Windows version info file from pyproject.toml."
    )
    parser.add_argument(
        "--output",
        "-o",
        type=Path,
        help="Output file path (default: stdout).",
    )
    args = parser.parse_args(argv)

    pyproject_path = Path(__file__).parent.parent / "pyproject.toml"
    with open(pyproject_path, "rb") as f:
        data: dict[str, Any] = tomllib.load(f)

    project: dict[str, Any] = data["project"]
    version_str = str(project["version"])
    version = _parse_version(version_str)
    name = str(project.get("name", "imap-cleanup"))
    description = str(project.get("description", ""))
    raw_authors: list[Any] = list(project.get("authors") or [])
    author = str(raw_authors[0].get("name", "")) if raw_authors else ""
    urls: dict[str, Any] = dict(data.get("project", {}).get("urls") or {})
    url = str(urls.get("Homepage", ""))

    lines = [
        "# Auto-generated by scripts/generate_version_info.py — do not edit manually.",
        "VSVersionInfo(",
        "  ffi=FixedFileInfo(",
        f"    filevers={version},",
        f"    prodvers={version},",
        "    mask=0x3f,",
        "    flags=0x0,",
        "    OS=0x40004,",
        "    fileType=0x1,",
        "    subtype=0x0,",
        "    date=(0, 0)",
        "    ),",
        "  kids=[",
        "    StringFileInfo(",
        "      [",
        "      StringTable(",
        "        u'040904B0',",
        f"        [StringStruct(u'CompanyName', u'{author}'),",
        f"        StringStruct(u'FileDescription', u'{description}'),",
        f"        StringStruct(u'FileVersion', u'{version_str}'),",
        f"        StringStruct(u'InternalName', u'{name}'),",
        f"        StringStruct(u'LegalCopyright', u'Copyright (c) {author}'),",
        f"        StringStruct(u'OriginalFilename', u'{name}-windows-x86_64.exe'),",
        "        StringStruct(u'ProductName', u'IMAP Cleanup'),",
        f"        StringStruct(u'ProductVersion', u'{version_str}'),",
        f"        StringStruct(u'Comments', u'{url}')])",
        "      ]),",
        "    VarFileInfo([VarStruct(u'Translation', [1033, 1200])])",
        "  ]",
        ")",
        "",
    ]
    content = "\n".join(lines)

    if args.output:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(content, encoding="utf-8")
        print(f"Written to {args.output}", file=sys.stderr)
    else:
        sys.stdout.write(content)

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
