name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened

  workflow_dispatch:

permissions:
  actions: read
  contents: read
  issues: read
  pull-requests: read
  security-events: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.event_name != 'push' }}

jobs:
  ci:
    name: ci
    uses: ./.github/workflows/_ci.yml
    permissions:
      contents: read

  codeql:
    name: CodeQL analysis
    needs: ci
    permissions:
      actions: read
      contents: read
      security-events: write
    uses: ./.github/workflows/_codeql.yml

  build-binaries:
    name: Build binaries
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: ci
    uses: ./.github/workflows/_build-binaries.yml
    permissions:
      contents: read

  semantic-tag:
    name: Semantic release
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: [codeql, build-binaries]
    uses: ./.github/workflows/_semantic-release.yml
    permissions:
      contents: write
      issues: write
      pull-requests: write
